

/****** Object:  Table [dbo].[BATCH_INFO]    Script Date: 5/3/2016 1:51:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BATCH_INFO](
	[BATCH_ID] [int] IDENTITY(1,1) NOT NULL,
	[BATCH_NM] [varchar](200) NOT NULL,
	[START_TM] [datetime] NOT NULL,
	[END_TM] [datetime] NULL,
	[SRC_REC_CNT] [int] NOT NULL,
	[TRG_REC_CNT] [int] NULL,
 CONSTRAINT [PK_BATCH] PRIMARY KEY CLUSTERED 
(
	[BATCH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

